# Generated by Django 2.2.5 on 2020-09-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200907_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='beths',
            new_name='baths',
        ),
    ]
