# Generated by Django 2.2.5 on 2020-09-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200907_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='geust',
            new_name='guest',
        ),
    ]
